name: ZincSearch
description:
  en: Enhance DooTask's search functionality with minimal resource consumption.
  zh: 以最小资源消耗增强 DooTask 的搜索功能。
author: Community
website: https://zincsearch-docs.zinc.dev/
github: https://github.com/zincsearch/zincsearch
document: https://zincsearch-docs.zinc.dev/
tags:
  - 搜索增强
  - 搜索引擎