name: ZincSearch
description:
  en: A lightweight search engine that enhances DooTask's search capabilities with minimal resource usage.
  zh: 一个轻量级搜索引擎，以最小资源消耗增强 DooTask 的搜索功能。
author: Community
website: https://zincsearch-docs.zinc.dev/
github: https://github.com/zincsearch/zincsearch
document: https://zincsearch-docs.zinc.dev/
tags:
  - 搜索增强
  - 搜索引擎
fields:
  - name: SEARCH_CPU
    label:
      en: CPU Limit
      zh: CPU 限制
    placeholder:
      en: Max CPU Limit
      zh: 最大 CPU 限制
    type: text
    default: 2
  - name: SEARCH_MEMORY
    label:
      en: Memory Limit
      zh: 内存限制
    placeholder:
      en: Max Memory Limit
      zh: 最大内存限制
    type: text
    default: 2G