// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://www.dootask.com",
        "contact": {
            "name": "DooTask团队",
            "url": "https://www.dootask.com",
            "email": "support@dootask.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/apps/download": {
            "post": {
                "description": "通过URL下载并安装应用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "通过URL下载应用",
                "parameters": [
                    {
                        "description": "下载参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AppInternalDownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/internal/apps/update": {
            "get": {
                "description": "从远程仓库更新应用列表，给 DooTask 内部应用商店使用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "更新应用列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/internal/apps/upload": {
            "post": {
                "description": "上传本地应用",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "上传本地应用",
                "parameters": [
                    {
                        "type": "file",
                        "description": "应用文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "应用ID，留空则从文件名自动提取",
                        "name": "appid",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/internal/install": {
            "post": {
                "description": "安装或更新应用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "安装应用",
                "parameters": [
                    {
                        "description": "安装参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AppInternalInstallRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/internal/installed": {
            "get": {
                "description": "获取所有已安装的应用列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "获取已安装应用列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.AppInternalInstalledResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/internal/log/{appId}": {
            "get": {
                "description": "获取指定应用的运行日志",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "获取应用日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用ID",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 2000,
                        "minimum": 1,
                        "type": "integer",
                        "default": 200,
                        "description": "行数",
                        "name": "n",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/internal/uninstall/{appId}": {
            "get": {
                "description": "卸载指定的应用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "卸载应用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用ID",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/list": {
            "get": {
                "description": "获取所有可用的应用列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用"
                ],
                "summary": "获取应用列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用ID列表，多个应用ID用逗号分隔",
                        "name": "appIds",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.App"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/one/{appId}": {
            "get": {
                "description": "获取指定应用的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用"
                ],
                "summary": "获取应用详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用ID",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.App"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/readme/{appId}": {
            "get": {
                "description": "获取指定应用的README文件内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用"
                ],
                "summary": "获取应用自述文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用ID",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/sources/package": {
            "get": {
                "description": "获取应用商店源列表压缩包",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/gzip"
                ],
                "tags": [
                    "资源"
                ],
                "summary": "应用商店源列表",
                "responses": {
                    "200": {
                        "description": "sources.tar.gz",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.App": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/models.AppConfig"
                },
                "description": {},
                "document": {
                    "type": "string"
                },
                "download_url": {
                    "type": "string"
                },
                "downloads": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FieldConfig"
                    }
                },
                "github": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "menu_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MenuItem"
                    }
                },
                "name": {},
                "rating": {
                    "type": "number"
                },
                "require_uninstalls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RequireUninstall"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "upgradeable": {
                    "type": "boolean"
                },
                "user_count": {
                    "type": "string"
                },
                "versions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "models.AppConfig": {
            "type": "object",
            "properties": {
                "install_at": {
                    "type": "string"
                },
                "install_num": {
                    "type": "integer"
                },
                "install_version": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": true
                },
                "resources": {
                    "$ref": "#/definitions/models.AppConfigResources"
                },
                "status": {
                    "description": "installing, installed, uninstalling, not_installed, error",
                    "type": "string"
                }
            }
        },
        "models.AppConfigResources": {
            "type": "object",
            "properties": {
                "cpu_limit": {
                    "type": "string"
                },
                "memory_limit": {
                    "type": "string"
                }
            }
        },
        "models.AppInternalDownloadRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "appid": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.AppInternalInstallRequest": {
            "type": "object",
            "required": [
                "appid"
            ],
            "properties": {
                "appid": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": true
                },
                "resources": {
                    "$ref": "#/definitions/models.AppConfigResources"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.AppInternalInstalledResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "menu_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MenuItem"
                    }
                }
            }
        },
        "models.FieldConfig": {
            "type": "object",
            "properties": {
                "default": {},
                "label": {},
                "name": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FieldOption"
                    }
                },
                "placeholder": {},
                "required": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.FieldOption": {
            "type": "object",
            "properties": {
                "label": {},
                "value": {
                    "type": "string"
                }
            }
        },
        "models.MenuItem": {
            "type": "object",
            "properties": {
                "autoDarkTheme": {
                    "type": "boolean"
                },
                "icon": {
                    "type": "string"
                },
                "keepAlive": {
                    "type": "boolean"
                },
                "label": {},
                "location": {
                    "type": "string"
                },
                "transparent": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.RequireUninstall": {
            "type": "object",
            "properties": {
                "operator": {
                    "type": "string"
                },
                "reason": {},
                "version": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DooTask应用商店API",
	Description:      "DooTask应用商店后端服务API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
