name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    name: Build ${{ matrix.mode }} image
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-latest"
            tags: "dootask/appstore:latest,dootask/appstore:${{ github.ref_name }}"
            mode: "internal"
          - platform: "ubuntu-latest"
            tags: "dootask/appstore:website,dootask/appstore:website-${{ github.ref_name }}"
            mode: "website"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.tags }}
          build-args: |
            MODE=${{ matrix.mode }}
          cache-from: type=gha,scope=${{ matrix.mode }}
          cache-to: type=gha,mode=max,scope=${{ matrix.mode }}

      - name: Build Status Notification
        if: always()
        run: |
          echo "::notice::Docker Image (${{ matrix.mode }}) - ${{ job.status == 'success' && '✅ Success' || '❌ Failed' }}"
          echo "::notice::Tag: ${{ github.ref_name }}"
          echo "::notice::Image: ${{ matrix.tags }}"
