name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tags and build args
        id: docker_tags
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAGS="dootask/appstore:latest,dootask/appstore:${{ github.ref_name }}"
            BASE_PATH="/appstore/"
          elif [[ "${{ github.ref_type }}" == "branch" ]]; then
            BRANCH_TAG=$(echo "${{ github.ref_name }}" | sed 's|/|-|g')
            TAGS="dootask/appstore:$BRANCH_TAG"
            BASE_PATH="/"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "base_path=$BASE_PATH" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          build-args: |
            VITE_BASE_PATH=${{ steps.docker_tags.outputs.base_path }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Status Notification
        if: always()
        run: |
          echo "::notice::Docker Image Build ${${{ job.status == 'success' && 'Success' || 'Failed' }}"
          echo "::notice::Branch/Tag: ${{ github.ref_name }}"
          echo "::notice::Image Tags: ${{ steps.docker_tags.outputs.tags }}"
          echo "::notice::VITE_BASE_PATH: ${{ steps.docker_tags.outputs.base_path }}"
